import { existsSync, readdirSync, statSync } from 'node:fs';
import { createReadStream } from 'node:fs';
import { createInterface } from 'node:readline';
import { homedir } from 'node:os';
import { basename, dirname, join } from 'node:path';

export type AssistantUsage = {
  // Unique event id — prefer message.id (msg_…), fall back to event uuid.
  eventId: string;
  sessionId: string;
  timestamp: string;
  model: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  // Encoded project directory string from the path under ~/.claude/projects/<this>.
  projectDirEncoded: string;
};

export type SessionMeta = {
  sessionId: string;
  title: string | null;
  projectDirEncoded: string;
  firstSeenAt: string | null;
  lastSeenAt: string | null;
};

// Walk session JSONL files and extract one SessionMeta per file. Title is
// the first non-empty user text message, truncated. Cheap second pass —
// reads each file separately from the usage-event stream so memory is
// bounded per file rather than across the whole project.
export async function* readSessionMetas(
  files: string[]
): AsyncGenerator<SessionMeta> {
  for (const file of files) {
    const projectDirEncoded = basename(dirname(file));
    const sessionId = basename(file, '.jsonl');
    let title: string | null = null;
    let firstSeenAt: string | null = null;
    let lastSeenAt: string | null = null;

    const stream = createReadStream(file, { encoding: 'utf8' });
    const lines = createInterface({ input: stream, crlfDelay: Infinity });
    for await (const raw of lines) {
      if (!raw.trim()) continue;
      let row: unknown;
      try {
        row = JSON.parse(raw);
      } catch {
        continue;
      }
      if (!isRecord(row)) continue;
      const ts = asString(row.timestamp);
      if (ts) {
        if (!firstSeenAt || ts < firstSeenAt) firstSeenAt = ts;
        if (!lastSeenAt || ts > lastSeenAt) lastSeenAt = ts;
      }
      if (!title && row.type === 'user') {
        const t = extractFirstUserText(row.message);
        if (t) title = truncate(t, 200);
      }
    }

    yield {
      sessionId,
      title,
      projectDirEncoded,
      firstSeenAt,
      lastSeenAt,
    };
  }
}

function extractFirstUserText(msg: unknown): string | null {
  if (!isRecord(msg)) return null;
  const content = msg.content;
  if (typeof content === 'string') {
    if (isNoiseText(content)) return null;
    return cleanTitle(content);
  }
  if (!Array.isArray(content)) return null;
  for (const block of content) {
    if (!isRecord(block)) continue;
    if (block.type !== 'text') continue;
    const t = asString(block.text);
    if (!t) continue;
    // Skip the giant hook-injected system context that some sessions get.
    if (isNoiseText(t)) continue;
    const cleaned = cleanTitle(t);
    if (cleaned) return cleaned;
  }
  return null;
}

// First-pass skip for whole-message noise: system reminders, the
// "Caveat: The messages below were generated by the user while running
// local commands" wrapper Claude Code injects for slash-command sessions,
// and the local-command stdout/stderr envelopes.
function isNoiseText(t: string): boolean {
  const s = t.trimStart();
  if (s.startsWith('<system-reminder>')) return true;
  if (s.startsWith('<local-command-')) return true;
  // Bare slash command with no args — e.g. /clear, /compact, /init.
  // These are session-lifecycle commands, not task prompts. A slash
  // command WITH args (e.g. "/superpowers:brainstorming Research…") is
  // meaningful and kept.
  if (/^\/[a-z0-9:_-]+\s*$/i.test(s)) return true;
  return false;
}

// Strip <command-message>/<command-name>/<command-args> wrappers around
// slash-command invocations so the visible title is the command + args,
// not the markup. Keep the useful command identifier when present.
function cleanTitle(raw: string): string | null {
  let s = raw.trim();
  // Pull out command pieces if present.
  const name = s.match(/<command-name>([^<]+)<\/command-name>/i)?.[1]?.trim();
  const args = s.match(/<command-args>([\s\S]*?)<\/command-args>/i)?.[1]?.trim();
  if (name) {
    // Bare lifecycle commands (/clear, /init, /compact) are not task
    // titles. Keep only commands that came with arguments.
    if (!args || args.trim() === '') return null;
    return `${name} ${args}`;
  }
  // No command markup — strip any stray angle-bracket tags and return body.
  s = s.replace(/<[^>]+>/g, '').trim();
  return s.length > 0 ? s : null;
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1).trimEnd() + '…';
}

export function claudeProjectsDir(): string {
  const envDir = process.env.CLAUDE_CONFIG_DIR;
  if (envDir) return join(envDir, 'projects');
  return join(homedir(), '.claude', 'projects');
}

export function listSessionFiles(root = claudeProjectsDir()): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  for (const projectName of safeReaddir(root)) {
    const projectPath = join(root, projectName);
    if (!safeIsDir(projectPath)) continue;
    for (const file of safeReaddir(projectPath)) {
      if (!file.endsWith('.jsonl')) continue;
      out.push(join(projectPath, file));
    }
  }
  return out;
}

export async function* readUsageEvents(
  files: string[]
): AsyncGenerator<AssistantUsage> {
  for (const file of files) {
    const projectDirEncoded = basename(dirname(file));
    const sessionIdFromName = basename(file, '.jsonl');
    const stream = createReadStream(file, { encoding: 'utf8' });
    const lines = createInterface({ input: stream, crlfDelay: Infinity });
    for await (const raw of lines) {
      if (!raw.trim()) continue;
      let row: unknown;
      try {
        row = JSON.parse(raw);
      } catch {
        continue;
      }
      const usage = extractAssistantUsage(row, sessionIdFromName, projectDirEncoded);
      if (usage) yield usage;
    }
  }
}

function extractAssistantUsage(
  row: unknown,
  sessionFallback: string,
  projectDirEncoded: string
): AssistantUsage | null {
  if (!isRecord(row)) return null;
  if (row.type !== 'assistant') return null;
  const msg = row.message;
  if (!isRecord(msg)) return null;
  const usage = msg.usage;
  if (!isRecord(usage)) return null;

  const eventId =
    asString(msg.id) ?? asString(row.uuid) ?? `${asString(row.timestamp)}-${Math.random()}`;
  const sessionId = asString(row.sessionId) ?? sessionFallback;
  const timestamp = asString(row.timestamp) ?? new Date().toISOString();
  const model = asString(msg.model) ?? 'unknown';

  return {
    eventId,
    sessionId,
    timestamp,
    model,
    projectDirEncoded,
    inputTokens: asNumber(usage.input_tokens) ?? 0,
    outputTokens: asNumber(usage.output_tokens) ?? 0,
    cacheReadTokens: asNumber(usage.cache_read_input_tokens) ?? 0,
    cacheWriteTokens: asNumber(usage.cache_creation_input_tokens) ?? 0,
  };
}

function safeReaddir(p: string): string[] {
  try {
    return readdirSync(p);
  } catch {
    return [];
  }
}

function safeIsDir(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function asString(v: unknown): string | null {
  return typeof v === 'string' && v.length > 0 ? v : null;
}

function asNumber(v: unknown): number | null {
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}
