import { existsSync, readdirSync, statSync } from 'node:fs';
import { createReadStream } from 'node:fs';
import { homedir } from 'node:os';
import { basename, dirname, join } from 'node:path';

export type AssistantUsage = {
  // Unique event id — prefer message.id (msg_…), fall back to event uuid.
  eventId: string;
  sessionId: string;
  timestamp: string;
  model: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  // Encoded project directory string from the path under ~/.claude/projects/<this>.
  projectDirEncoded: string;
};

export type SessionMeta = {
  sessionId: string;
  title: string | null;
  projectDirEncoded: string;
  firstSeenAt: string | null;
  lastSeenAt: string | null;
};

export type SessionScan = {
  meta: SessionMeta;
  // Absolute byte offset just past the last line this scan parsed. Feed it
  // back as `start` next time to read only what was appended since.
  consumedBytes: number;
};

// Scan one session transcript in a single pass, starting at byte `start`.
// Emits every assistant usage event through `onUsage` and collects the
// per-file SessionMeta (title, time bounds) from the same parse — the
// file is read and JSON-parsed exactly once.
//
// Byte accounting makes tail reads safe on append-only transcripts:
// lines are split on raw \n bytes (never a UTF-8 continuation byte), and
// consumedBytes only advances past lines that were actually parsed. A
// trailing fragment with no newline is parsed only if it is valid JSON
// (a complete line the writer just hadn't newline-terminated yet); an
// unparseable fragment is a mid-write line, so consumedBytes stops before
// it and the next scan re-reads the whole line once it's complete.
//
// A tail scan (start > 0) can't see the session's opening lines, so
// meta.title may be null and firstSeenAt reflects only the tail; callers
// must merge against previously stored values rather than overwrite.
export async function scanSessionFile(
  file: string,
  start: number,
  onUsage: (usage: AssistantUsage) => void
): Promise<SessionScan> {
  const projectDirEncoded = basename(dirname(file));
  const sessionId = basename(file, '.jsonl');
  let title: string | null = null;
  let firstSeenAt: string | null = null;
  let lastSeenAt: string | null = null;
  let consumedBytes = start;

  const processLine = (raw: string): void => {
    if (!raw.trim()) return;
    let row: unknown;
    try {
      row = JSON.parse(raw);
    } catch {
      return;
    }
    const usage = extractAssistantUsage(row, sessionId, projectDirEncoded);
    if (usage) onUsage(usage);
    if (!isRecord(row)) return;
    const ts = asString(row.timestamp);
    if (ts) {
      if (!firstSeenAt || ts < firstSeenAt) firstSeenAt = ts;
      if (!lastSeenAt || ts > lastSeenAt) lastSeenAt = ts;
    }
    if (!title && row.type === 'user') {
      const t = extractFirstUserText(row.message);
      if (t) title = truncate(t, 200);
    }
  };

  const stream = createReadStream(file, { start });
  let leftover: Buffer = Buffer.alloc(0);
  for await (const chunk of stream as AsyncIterable<Buffer>) {
    let data = leftover.length > 0 ? Buffer.concat([leftover, chunk]) : chunk;
    let nl: number;
    while ((nl = data.indexOf(0x0a)) !== -1) {
      const lineEnd = nl > 0 && data[nl - 1] === 0x0d ? nl - 1 : nl;
      processLine(data.subarray(0, lineEnd).toString('utf8'));
      consumedBytes += nl + 1;
      data = data.subarray(nl + 1);
    }
    leftover = data;
  }
  if (leftover.length > 0) {
    // No trailing newline. Parse the remainder only if it's a complete
    // JSON line; JSON.parse of a truncated object always throws, so a
    // mid-write fragment never advances the watermark.
    const raw = leftover.toString('utf8');
    try {
      JSON.parse(raw);
      processLine(raw);
      consumedBytes += leftover.length;
    } catch {
      // fragment — leave for the next scan
    }
  }

  return {
    meta: { sessionId, title, projectDirEncoded, firstSeenAt, lastSeenAt },
    consumedBytes,
  };
}

function extractFirstUserText(msg: unknown): string | null {
  if (!isRecord(msg)) return null;
  const content = msg.content;
  if (typeof content === 'string') {
    if (isNoiseText(content)) return null;
    return cleanTitle(content);
  }
  if (!Array.isArray(content)) return null;
  for (const block of content) {
    if (!isRecord(block)) continue;
    if (block.type !== 'text') continue;
    const t = asString(block.text);
    if (!t) continue;
    // Skip the giant hook-injected system context that some sessions get.
    if (isNoiseText(t)) continue;
    const cleaned = cleanTitle(t);
    if (cleaned) return cleaned;
  }
  return null;
}

// First-pass skip for whole-message noise: system reminders, the
// "Caveat: The messages below were generated by the user while running
// local commands" wrapper Claude Code injects for slash-command sessions,
// and the local-command stdout/stderr envelopes.
function isNoiseText(t: string): boolean {
  const s = t.trimStart();
  if (s.startsWith('<system-reminder>')) return true;
  if (s.startsWith('<local-command-')) return true;
  // Bare slash command with no args — e.g. /clear, /compact, /init.
  // These are session-lifecycle commands, not task prompts. A slash
  // command WITH args (e.g. "/superpowers:brainstorming Research…") is
  // meaningful and kept.
  if (/^\/[a-z0-9:_-]+\s*$/i.test(s)) return true;
  return false;
}

// Strip <command-message>/<command-name>/<command-args> wrappers around
// slash-command invocations so the visible title is the command + args,
// not the markup. Keep the useful command identifier when present.
function cleanTitle(raw: string): string | null {
  let s = raw.trim();
  // Pull out command pieces if present.
  const name = s.match(/<command-name>([^<]+)<\/command-name>/i)?.[1]?.trim();
  const args = s.match(/<command-args>([\s\S]*?)<\/command-args>/i)?.[1]?.trim();
  if (name) {
    // Bare lifecycle commands (/clear, /init, /compact) are not task
    // titles. Keep only commands that came with arguments.
    if (!args || args.trim() === '') return null;
    return `${name} ${args}`;
  }
  // No command markup — strip any stray angle-bracket tags and return body.
  s = s.replace(/<[^>]+>/g, '').trim();
  return s.length > 0 ? s : null;
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1).trimEnd() + '…';
}

export function claudeProjectsDir(): string {
  const envDir = process.env.CLAUDE_CONFIG_DIR;
  if (envDir) return join(envDir, 'projects');
  return join(homedir(), '.claude', 'projects');
}

export function listSessionFiles(root = claudeProjectsDir()): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  for (const projectName of safeReaddir(root)) {
    const projectPath = join(root, projectName);
    if (!safeIsDir(projectPath)) continue;
    for (const file of safeReaddir(projectPath)) {
      if (!file.endsWith('.jsonl')) continue;
      out.push(join(projectPath, file));
    }
  }
  return out;
}

function extractAssistantUsage(
  row: unknown,
  sessionFallback: string,
  projectDirEncoded: string
): AssistantUsage | null {
  if (!isRecord(row)) return null;
  if (row.type !== 'assistant') return null;
  const msg = row.message;
  if (!isRecord(msg)) return null;
  const usage = msg.usage;
  if (!isRecord(usage)) return null;

  const eventId =
    asString(msg.id) ?? asString(row.uuid) ?? `${asString(row.timestamp)}-${Math.random()}`;
  const sessionId = asString(row.sessionId) ?? sessionFallback;
  const timestamp = asString(row.timestamp) ?? new Date().toISOString();
  const model = asString(msg.model) ?? 'unknown';

  return {
    eventId,
    sessionId,
    timestamp,
    model,
    projectDirEncoded,
    inputTokens: asNumber(usage.input_tokens) ?? 0,
    outputTokens: asNumber(usage.output_tokens) ?? 0,
    cacheReadTokens: asNumber(usage.cache_read_input_tokens) ?? 0,
    cacheWriteTokens: asNumber(usage.cache_creation_input_tokens) ?? 0,
  };
}

function safeReaddir(p: string): string[] {
  try {
    return readdirSync(p);
  } catch {
    return [];
  }
}

function safeIsDir(p: string): boolean {
  try {
    return statSync(p).isDirectory();
  } catch {
    return false;
  }
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function asString(v: unknown): string | null {
  return typeof v === 'string' && v.length > 0 ? v : null;
}

function asNumber(v: unknown): number | null {
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}
